"""empty message

Revision ID: 47ef9fd0d17f
Revises: fbf4bb56cee1
Create Date: 2023-12-02 11:10:23.315233

"""
import os, json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, MetaData

# revision identifiers, used by Alembic.
revision: str = '47ef9fd0d17f'
down_revision: Union[str, None] = 'fbf4bb56cee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Date


def upgrade() -> None:
    meta = MetaData('public')  # bind=op.get_bind()
    meta.reflect(only=('users',), bind=op.get_bind())
    # users = sa.Table('users', meta, schema='public')
    users = table('users',
                  column('id', Integer),
                  column('email', String),
                  )
    print('meta', meta)
    print('users', users)    
    
    # ### commands auto generated by Alembic - please adjust! ###
    with open(os.path.join(os.path.dirname(__file__), "../data/students.json")) as f:
        student_data = f.read()
        print('student_data', student_data)

    op.bulk_insert(users, json.loads(student_data))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_courses', schema='public', type_='foreignkey')
    op.create_foreign_key('student_courses_course_id_fkey', 'student_courses', 'courses', ['course_id'], ['id'])
    op.create_foreign_key('student_courses_student_id_fkey', 'student_courses', 'users', ['student_id'], ['id'])
    op.drop_constraint(None, 'sections', schema='public', type_='foreignkey')
    op.create_foreign_key('sections_course_id_fkey', 'sections', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'profiles', schema='public', type_='foreignkey')
    op.create_foreign_key('profiles_user_id_fkey', 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'courses', schema='public', type_='foreignkey')
    op.create_foreign_key('courses_user_id_fkey', 'courses', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'content_blocks', schema='public', type_='foreignkey')
    op.create_foreign_key('content_blocks_section_id_fkey', 'content_blocks', 'sections', ['section_id'], ['id'])
    op.drop_constraint(None, 'completed_content_blocks', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'completed_content_blocks', schema='public', type_='foreignkey')
    op.create_foreign_key('completed_content_blocks_content_block_id_fkey', 'completed_content_blocks', 'content_blocks', ['content_block_id'], ['id'])
    op.create_foreign_key('completed_content_blocks_student_id_fkey', 'completed_content_blocks', 'users', ['student_id'], ['id'])
    # ### end Alembic commands ###
