"""empty message

Revision ID: fbf4bb56cee1
Revises: 90f3dd23add1
Create Date: 2023-12-02 08:42:20.865504

"""
import os, json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Table, MetaData

meta = MetaData()  # bind=op.get_bind()
users = sa.Table('users', meta, schema='public')

# revision identifiers, used by Alembic.
revision: str = 'fbf4bb56cee1'
down_revision: Union[str, None] = '90f3dd23add1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('sections_course_id_fkey', 'sections', type_='foreignkey')
    op.create_foreign_key(None, 'sections', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('student_courses_student_id_fkey', 'student_courses', type_='foreignkey')
    op.drop_constraint('student_courses_course_id_fkey', 'student_courses', type_='foreignkey')
    op.create_foreign_key(None, 'student_courses', 'courses', ['course_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'student_courses', 'users', ['student_id'], ['id'], source_schema='public', referent_schema='public')
    
    with open(os.path.join(os.path.dirname(__file__), "../data/students.json")) as f:
        student_data = f.read()
        print('student_data', student_data)

    op.bulk_insert(users, json.loads(student_data))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_courses', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'student_courses', schema='public', type_='foreignkey')
    op.create_foreign_key('student_courses_course_id_fkey', 'student_courses', 'courses', ['course_id'], ['id'])
    op.create_foreign_key('student_courses_student_id_fkey', 'student_courses', 'users', ['student_id'], ['id'])
    op.drop_constraint(None, 'sections', schema='public', type_='foreignkey')
    op.create_foreign_key('sections_course_id_fkey', 'sections', 'courses', ['course_id'], ['id'])
    op.drop_constraint(None, 'profiles', schema='public', type_='foreignkey')
    op.create_foreign_key('profiles_user_id_fkey', 'profiles', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'courses', schema='public', type_='foreignkey')
    op.create_foreign_key('courses_user_id_fkey', 'courses', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'content_blocks', schema='public', type_='foreignkey')
    op.create_foreign_key('content_blocks_section_id_fkey', 'content_blocks', 'sections', ['section_id'], ['id'])
    op.drop_constraint(None, 'completed_content_blocks', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'completed_content_blocks', schema='public', type_='foreignkey')
    op.create_foreign_key('completed_content_blocks_student_id_fkey', 'completed_content_blocks', 'users', ['student_id'], ['id'])
    op.create_foreign_key('completed_content_blocks_content_block_id_fkey', 'completed_content_blocks', 'content_blocks', ['content_block_id'], ['id'])
    # ### end Alembic commands ###
